class QuarterCycleCounterStates(object):
    OFF = 0
    PREPARED = 1
    ARMED = 2
    TRIPPED = 4
    PREPARED_WITH_GLOBAL_DISARM_INHIBITED = 6
    ARMED_WITH_GLOBAL_DISARM_INHIBITED = 7
    TRIPPED_WITH_GLOBAL_DISARM_INHIBITED = 9
